### PR TITLE
Importing CF Localizations, fixing Addon list naming

### PR DESCRIPTION
**Pull request by Rycia**

### CODE REVIEW

**Comment by Rycia** [comment]
error 1
```
2x APR-Core/Core.lua:526: attempt to index local 'L' (a nil value)
[string "@APR-Core/Core.lua"]:526: in main chunk

Locals:
app = <table> {
}
L = nil
CoreLoadin = 0
t = Texture {
 0 = <userdata>
}
PlayMovie_hook = <function> defined @FrameXML/MovieFrame.lua:20
APR_SlashCmd = <function> defined @APR-Core/Core.lua:422
t = Texture {
 0 = <userdata>
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = CLSettingsFS2212 {
 0 = <userdata>
}
(*temporary) = "CENTER"
(*temporary) = APR_ArrowActiveButton {
 0 = <userdata>
 texture = Texture {
 }
}
(*temporary) = <userdata>
(*temporary) = "ARTWORK"
(*temporary) = "ChatFontNormal"
(*temporary) = "attempt to index local 'L' (a nil value)"
```

**Comment by Rycia** [comment]
error 2
```
1x APR-Core/OptionsPanel.lua:13: attempt to concatenate field 'Version' (a nil value)
[string "@APR-Core/OptionsPanel.lua"]:13: in main chunk

Locals:
app = <table> {
}
L = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = SimpleHTML {
 0 = <userdata>
}
(*temporary) = "Azeroth Pilot Reloaded - "
(*temporary) = nil
(*temporary) = 0
(*temporary) = -30
(*temporary) = <userdata>
(*temporary) = "attempt to concatenate field 'Version' (a nil value)"

```

**Comment by Rycia** [comment]
error 4
```
2x APR-Core/zones/Horde.lua:131: attempt to index field 'Shadowlands' (a nil value)
[string "@APR-Core/zones/Horde.lua"]:131: in main chunk

Locals:
(*temporary) = nil
(*temporary) = <table> {
 641-ValSharah = "Legion - Val'Sharah"
 862-Zuldazar-1 = "10-50 Zuldazar"
 634-Stormheim = "Legion - Stormheim"
 1-Orgrimmar = "10-10 BFA Intro"
 630-Azsuna = "Legion - Azsuna"
 864-Vol'dun = "30-50 Vol'dun"
 862-Zuldazar-2 = "30-30 Naz-end Vol-begin"
 862-Zuldazar = "10-10 BFA intro 2"
 863-Nazmir = "20-50 Nazmir"
}
(*temporary) = "attempt to index field 'Shadowlands' (a nil value)"
```

**Comment by Rycia** [comment]
error 5
```
2x APR-Core/QuestList.lua:102: attempt to index upvalue 'L' (a nil value)
[string "@APR-Core/QuestList.lua"]:102: in function <APR-Core/QuestList.lua:27>
[string "@APR-Core/QuestList.lua"]:798: in function <APR-Core/QuestList.lua:794>

Locals:
CLi = nil
(for index) = 1
(for limit) = 5
(for step) = 1
CLi = 1
t = Texture {
 0 = <userdata>
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = CLQaasFS1 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = "LEFT"
(*temporary) = 5
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = CLQaasFS1 {
 0 = <userdata>
}
(*temporary) = "CLQaasFS1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'L' (a nil value)"
L = nil
```

**Comment by Rycia** [comment]
error 6 (huge problem)
```
33795x APR-Core/QuestHandler.lua:176: attempt to index field '?' (a nil value)
[string "@APR-Core/QuestHandler.lua"]:176: in function `RemoveIcons'
[string "@APR-Core/QuestHandler.lua"]:2630: in function <APR-Core/QuestHandler.lua:2602>
[string "@APR-Core/QuestHandler.lua"]:2885: in function <APR-Core/QuestHandler.lua:2692>

Locals:
(for index) = 1
(for limit) = 20
(for step) = 1
CLi = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
```

**Comment by NightofStarrs** [comment]
Error 1:
Reason for L, not being correctly defined (nil value), the exports from Curseforge need to have 
`local app = select(2, ...);`
`local L = app.L;`

Error 2:
Issue with Version Number -- investigating

Error 3:
Register Event for Q_REMOVED
QUEST_ACCEPTED, QUEST_ACCEPT_CONFIRM, and QUEST_REMOVED are WoW Enum Register Events, these need to be left alone.

Error 4:
Shadowlands 'nil value'
This needs to have 'Shadowlands' changed to 'MISC 1' to properly fit the table.

Error 5:
Contininuation of Error 1.


Error 6:
Error with the RemoveIcons -- investigating

**Review by Neogeekmo — APPROVED** [review]

**Review by NightofStarrs — APPROVED** [review]

**Pull request merged**
